version: 2
jobs:
  build:
    docker:
      - image: ubuntu:xenial
    branches:
      only:
        - Lakka-V2.1-dev
    steps:
      - checkout
      - run:
          name: Install Host Dependencies
          command: apt-get update && apt-get install -y xz-utils make wget bash bc gcc sed patch patchutils tar bzip2 gzip perl gawk gperf zip unzip diffutils texinfo lzop libc6-dev libncurses5-dev g++ xfonts-utils xfonts-utils xfonts-utils xsltproc libjson-perl
      - run: echo 'export DISTRO=Lakka' >> $BASH_ENV
      - run: echo 'export PROJECT=Generic' >> $BASH_ENV
      - run: echo 'export ARCH=x86_64' >> $BASH_ENV
      - run: make image

